function image = Get_ROIs_Image(neurons,x,y,brightness,hues,saturation)
% Draw ROI clusters from  neurons data (generated by CaTrEx GUI)
%
%       image = Get_ROIs_Image(neurons,x,y,brightness,hues,saturation)
%
% Modified by Jesus Perez-Ortega, July 2019
% Modified Oct 2019
% Modified Dec 2019
% Modified Apr 2020

nCells = length(neurons);
switch (nargin)
    case 3
        brightness = 1;
        hues = [];
        saturation = 1;
    case 4
        hues = [];
        saturation = 1;
    case 5
        saturation = 1;
end

if isfield(neurons,'PSNR')
    brightness = [neurons.PSNR];
elseif length(brightness)==1
     brightness = brightness*ones(nCells,1);
end

if length(saturation)==1
     saturation = saturation*ones(nCells,1);
end

% Get hues
if isempty(hues)
    % tuning colors 
    % -2, locomotion correlated
    % -1, inter-stimulus correlated
    % 0, others
    % 1-8, orientation
    if isfield(neurons,'TuningID')
        colors_HSV = [0.9 0.2 0.9;...
                      0.8 0.5 0.9;...
                      0.0 0.0 0.0;...
                      0.0 0.9 0.9;... 
                      0.2 0.9 0.9;... 
                      0.4 0.9 0.9;... 
                      0.6 0.9 0.9;...
                      0.0 0.5 0.9;...
                      0.2 0.5 0.9;... 
                      0.4 0.5 0.9;... 
                      0.6 0.5 0.9];
        hues = zeros(nCells,1);
        for i = 1:nCells
            hues(i) = colors_HSV(neurons(i).TuningID+3,1);
            saturation(i) = colors_HSV(neurons(i).TuningID+3,2);
        end
    else
        % Put green color
        hues = 0.3*ones(nCells,1);
    end
elseif length(hues)==1
    hues = hues*ones(nCells,1);
end

% Set value/brighthness
value = zeros(y,x);
cells = zeros(y, x);
for i = 1:nCells
    value(neurons(i).pixels) = neurons(i).weight_pixels*brightness(i);
    cells(neurons(i).pixels) = i;
end
maxValue = quantile(value(value>0),0.95);
value(value>maxValue) = maxValue;
value = rescale(value,0.1,1);

% Get hues
hue = zeros(y, x);
hue(cells>0) = hues(cells(cells>0));
hue = reshape(hue, y, x);

% Get saturation
sat = zeros(y, x);
sat(cells>0) = saturation(cells(cells>0));
sat = reshape(sat, y, x);

% Create image
image = hsv2rgb(cat(3,hue,sat,value));