function image = Get_Neurons_Image(neurons,x,y,colors,blackBG,drawBoundaries)
% Get image of neurons from neurons data (generated by CaTrEx GUI)
%
%       image = Get_Neurons_Image(neurons,x,y,colors,blackBG,drawBoundaries)
%
% By Jesus Perez-Ortega, Apr 2020

switch (nargin)
    case 3
        colors = [1 1 1];
        blackBG = false;
        drawBoundaries = true;
    case 4
        blackBG = false;
        drawBoundaries = true;
    case 5
        drawBoundaries = true;
end

colors = rgb2hsv(colors);
hues = colors(:,1);
saturation = colors(:,2);
brightness = colors(:,3);

% Set all HSV values if only one is indicated
nCells = length(neurons);
if length(brightness)==1, brightness = brightness*ones(nCells,1); end
if length(saturation)==1, saturation = saturation*ones(nCells,1); end
if length(hues)==1, hues = hues*ones(nCells,1); end

% Set value/brighthness
if blackBG
    value = zeros(y,x);
else
    value = ones(y,x);
end
cells = zeros(y,x);
for i = 1:nCells
    value(neurons(i).pixels) = brightness(i);
    cells(neurons(i).pixels) = i;
end

% Set hue
hue = zeros(y,x);
hue(cells>0) = hues(cells(cells>0));
hue = reshape(hue,y,x);

% Set saturation
sat = zeros(y,x);
sat(cells>0) = saturation(cells(cells>0));
sat = reshape(sat,y,x);

% Create image
image = hsv2rgb(cat(3,hue,sat,value));

if drawBoundaries
    % Get boundaries from each cell
    boundaries = zeros(y,x);
    for i = 1:nCells
        white = zeros(y,x);
        white(neurons(i).pixels) = 1;
        boundaries = boundaries|boundarymask(white,4);
    end

    % Add boundaries to the image
    if blackBG
        image(:,:,1) = image(:,:,1)|boundaries;
        image(:,:,2) = image(:,:,2)|boundaries;
        image(:,:,3) = image(:,:,3)|boundaries;    
    else
        boundaries = ~boundaries;
        image(:,:,1) = image(:,:,1).*boundaries;
        image(:,:,2) = image(:,:,2).*boundaries;
        image(:,:,3) = image(:,:,3).*boundaries;    
    end
end
